name: Deploy to App Service

on:
  workflow_call:
    inputs:
      appName:
        description: The name of the App Service
        required: true
        type: string
      slot:
        description: The slot to deploy the application to
        default: production
        required: false
        type: string
      ref:
        description: The branch, tag or commit (SHA) to deploy
        default: main
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ApsSlotsDemo.App

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: dotnet publish
        run: dotnet publish -c Release -o publish/ApsSlotsDemo.App

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ inputs.appName }} 
          slot-name: ${{ inputs.slot }}
          package: ./src/ApsSlotsDemo.App/publish/ApsSlotsDemo.App
